name: testproject
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: install Node.jobs
        uses: actions/setup-node@v3
        node-version: '18'
      - name: install dependencies  
        run: npm ci
      - name: run tests
        run: npm test
        
